name: Issue
on:
   issues:
   
jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - run: |
            echo 'issue body: ${{ github.event.issue.body }}'
            # do something with the issue
      - run: |
            ./deploy.sh --secret ${{secrets.UPPERCASE_SECRET}}
