name: Security test
on:
  push:
  
jobs:
  security:
    runs-on: ubuntu-latest


    steps:
      - name: debug
        continue-on-error: true
        run: |
          echo "Hello"
      - name: debug
        run: echo "Hello"
        env:
          UPPERCASE_SECRET: ${{secrets.UPPERCASE_SECRET}}
