name: GitHub Actions
on: push
jobs:
  init:
    runs-on: ubuntu-latest
    steps:
      - name: install
        run: |
          # npm install dependencies...
          # do somethinng
        env:
          secret_REPO_SECRET: ${{secrets.REPO_SECRET}}
