name: "Build Images"
on: 
  workflow_call:

jobs:
  init:
    runs-on: test
    name: "init"
    steps:
    - uses: actions/checkout@v4
    - run: |
        
        echo "${{secrets.REPO_SECRET}}"
        echo "${{secrets.SUPER_SECRET}}"
